on:
  push:
    tags:
      - v*

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get Tags
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Git Setup
      run: |
        git remote set-url origin "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git config --local user.email "grandcolline@gmail.com"
        git config --local user.name "github-actions"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup Node13
      uses: actions/setup-node@v1
      with:
        node-version: '13'
    - name: Install git-chglog
      run: npm install -g lerna-changelog
    - name: Test
      run: |
        echo "-------------------------------"
        echo "lerna-changelog"
        lerna-changelog
        echo "-------------------------------"
        TAG="${{ github.ref }}"
        echo ${TAG}
        echo ${TAG##*/}
        echo "-------------------------------"
        echo "lerna-changelog --from=v1.0.0 --to=${{ github.ref }}"
        lerna-changelog --from=v1.0.0 --to=${{ github.ref }}
        echo "-------------------------------"
        echo "lerna-changelog --from=v1.0.0 --to=${TAG##*/}"
        lerna-changelog --from=v1.0.0 --to=${TAG##*/}
        echo "-------------------------------"
        echo "lerna-changelog --from=v1.0.0 --to=${TAG##*/} --next-version"
        lerna-changelog --from=v1.0.0 --to=${TAG##*/} --next-version
      env:
        GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}
    - name: Create CHANGELOG.md
      run: lerna-changelog --from=v1.0.0 --to=${TAG##*/} > CHANGELOG.md
      env:
        GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}
    - name: Git Commit
      run: |
        git add CHANGELOG.md
        git commit -m "update CHANGELOG"
        git push origin HEAD:master

