on:
  push:
    tags:
      - v*

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install git-chglog
      run: npm install -g lerna-changelog
    - name: Create CHANGELOG.md
      run: lerna-changelog --from=v1.0.0 --to=v2.0.2
      #    - name: Git Setup
      #      run: |
      #        git remote set-url origin "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
      #        git config --local user.email "grandcolline@gmail.com"
      #        git config --local user.name "github-actions"
      #      env:
      #        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #    - name: Git Commit
      #      run: |
      #        git add CHANGELOG.md
      #        git commit -m "update CHANGELOG"
      #        git push origin HEAD:master

